"use client";
import {useEffect,useState} from "react";
import type {DeveloperToolSlug} from "@/lib/developer-tools";
import {TrafficTool} from "@/components/developer/traffic-tool";
import {decodeBase64,decodeHtml,decodeJwt,dateToTimestamp,diffLines,encodeBase64,encodeHtml,formatJsonError,generateHash,generateSlug,generateUuidV4,timestampToDates,transformJson,transformUrl,validateJson,validateUuid,type DiffLine} from "@/lib/developer-utils";

const inputClass="mt-2 min-h-48 w-full resize-y rounded-xl border border-slate-300 bg-white p-4 font-mono text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const smallInputClass="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 font-mono outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const primaryClass="rounded-xl bg-[#315efb] px-4 py-2.5 font-semibold text-white disabled:opacity-50";
const secondaryClass="rounded-xl border border-slate-300 bg-white px-4 py-2.5 font-semibold text-slate-700";

function Panel({children}:{children:React.ReactNode}){return <section className="mt-8 rounded-2xl border bg-white p-5 shadow-sm sm:p-6">{children}</section>}
function Actions({children}:{children:React.ReactNode}){return <div className="mt-4 flex flex-wrap gap-2">{children}</div>}
function Status({message,error=false}:{message:string;error?:boolean}){return <div role="status" aria-live="polite" className={`mt-4 rounded-xl p-3 text-sm ${error?"bg-red-50 text-red-800":"bg-emerald-50 text-emerald-800"}`}>{message}</div>}
function CopyButton({value,label="Copy result"}:{value:string;label?:string}){const[copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1500);}catch{setCopied(false);}}return <button type="button" disabled={!value} onClick={copy} className={secondaryClass}>{copied?"Copied":label}</button>}
function Output({value,label="Output"}:{value:string;label?:string}){return <div className="mt-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">{label}</h2><CopyButton value={value}/></div><pre aria-live="polite" className="mt-2 max-h-[32rem] min-h-24 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-950 p-4 text-sm text-slate-100">{value||"Result will appear here."}</pre></div>}
function LabeledTextarea({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){const id=label.toLowerCase().replace(/\W+/g,"-");return <label htmlFor={id} className="block font-semibold">{label}<textarea id={id} maxLength={1_000_000} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} className={inputClass}/></label>}

function JsonTool({validator=false}:{validator?:boolean}){const[input,setInput]=useState("");const[output,setOutput]=useState("");const[status,setStatus]=useState<{text:string;error:boolean}|null>(null);function validate(){const result=validateJson(input);if(result.valid){setStatus({text:"Valid JSON syntax.",error:false});if(validator)setOutput(input);}else{setStatus({text:formatJsonError(result),error:true});setOutput("");}}function convert(compact:boolean){try{setOutput(transformJson(input,compact));setStatus({text:compact?"Valid JSON compacted without changing tokens.":"Valid JSON formatted without changing tokens.",error:false});}catch(error){setOutput("");setStatus({text:error instanceof Error?error.message:"Invalid JSON.",error:true});}}function clear(){setInput("");setOutput("");setStatus(null);}function example(){setInput('{"project":"SignalRate","active":true,"tools":["JSON","Base64"],"count":12}');setOutput("");setStatus(null);}return <Panel><LabeledTextarea label="JSON input" value={input} onChange={setInput} placeholder='{"message":"Hello"}'/><Actions>{validator?<button type="button" onClick={validate} className={primaryClass}>Validate JSON</button>:<><button type="button" onClick={()=>convert(false)} className={primaryClass}>Format</button><button type="button" onClick={()=>convert(true)} className={secondaryClass}>Compact</button><button type="button" onClick={validate} className={secondaryClass}>Validate</button></>}<button type="button" onClick={example} className={secondaryClass}>Use example</button><button type="button" onClick={clear} className={secondaryClass}>Clear</button></Actions>{status&&<Status message={status.text} error={status.error}/>}<Output value={output}/></Panel>}

function Base64Tool(){const[input,setInput]=useState("");const[output,setOutput]=useState("");const[urlSafe,setUrlSafe]=useState(false);const[error,setError]=useState("");function run(action:"encode"|"decode"){try{setOutput(action==="encode"?encodeBase64(input,urlSafe):decodeBase64(input,urlSafe));setError("");}catch(e){setOutput("");setError(e instanceof Error?e.message:"Unable to process input.");}}return <Panel><LabeledTextarea label="Text or Base64 input" value={input} onChange={setInput}/><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={urlSafe} onChange={e=>setUrlSafe(e.target.checked)}/> Use Base64URL alphabet</label><Actions><button type="button" onClick={()=>run("encode")} className={primaryClass}>Encode</button><button type="button" onClick={()=>run("decode")} className={secondaryClass}>Decode</button><button type="button" onClick={()=>setInput("Hello, 世界 👋")} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setInput("");setOutput("");setError("");}} className={secondaryClass}>Clear</button></Actions>{error&&<Status message={error} error/>}<Output value={output}/></Panel>}

function JwtTool(){const[input,setInput]=useState("");const[result,setResult]=useState<ReturnType<typeof decodeJwt>|null>(null);const[error,setError]=useState("");function run(){try{setResult(decodeJwt(input));setError("");}catch(e){setResult(null);setError(e instanceof Error?e.message:"Malformed JWT.");}}const output=result?JSON.stringify({header:result.header,payload:result.payload,signature_segment:result.signature,readable_claims:result.claims},null,2):"";return <Panel><LabeledTextarea label="JWT" value={input} onChange={setInput} placeholder="header.payload.signature"/><Actions><button type="button" onClick={run} className={primaryClass}>Decode token</button><button type="button" onClick={()=>setInput("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNzAwMDAwMDAwfQ.signature")} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setInput("");setResult(null);setError("");}} className={secondaryClass}>Clear</button></Actions><Status message="Decoded only — signature not verified." error={false}/>{error&&<Status message={error} error/>}<Output value={output} label="Decoded token"/></Panel>}

function UuidGenerator(){const[values,setValues]=useState<string[]>([]);const[count,setCount]=useState(1);function generate(){try{setValues(Array.from({length:count},generateUuidV4));}catch{setValues([]);}}return <Panel><label className="font-semibold">Quantity<select value={count} onChange={e=>setCount(Number(e.target.value))} className={smallInputClass}>{[1,5,10,100].map(value=><option key={value}>{value}</option>)}</select></label><Actions><button type="button" onClick={generate} className={primaryClass}>Generate UUIDs</button><button type="button" onClick={()=>{setCount(5);setValues(Array.from({length:5},generateUuidV4));}} className={secondaryClass}>Example: generate 5</button><button type="button" onClick={()=>setValues([])} className={secondaryClass}>Clear</button><CopyButton value={values.join("\n")} label="Copy all"/></Actions><div aria-live="polite" className="mt-5 space-y-2">{values.map(value=><div key={value} className="flex min-w-0 items-center gap-2 rounded-xl bg-slate-50 p-3"><code className="min-w-0 flex-1 break-all text-sm">{value}</code><CopyButton value={value} label="Copy"/></div>)}</div></Panel>}

function UuidValidator(){const[input,setInput]=useState("");const[result,setResult]=useState<ReturnType<typeof validateUuid>|null>(null);return <Panel><label className="font-semibold">UUID<input value={input} onChange={e=>setInput(e.target.value)} className={smallInputClass} placeholder="550e8400-e29b-41d4-a716-446655440000"/></label><Actions><button type="button" onClick={()=>setResult(validateUuid(input))} className={primaryClass}>Validate UUID</button><button type="button" onClick={()=>{setInput("550e8400-e29b-41d4-a716-446655440000");setResult(null);}} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setInput("");setResult(null);}} className={secondaryClass}>Clear</button></Actions>{result&&(result.valid?<Status message={`Valid UUID v${result.version}; ${result.variant}.`}/>:<Status message={result.message} error/>)}<Output value={result?.valid?result.normalized:""} label="Normalized UUID"/></Panel>}

function TimestampTool(){const[input,setInput]=useState("");const[unit,setUnit]=useState<"seconds"|"milliseconds">("seconds");const[dateInput,setDateInput]=useState("");const[output,setOutput]=useState("");const[error,setError]=useState("");const[now,setNow]=useState<number|null>(null);useEffect(()=>{const tick=()=>setNow(Math.floor(Date.now()/1000));const first=setTimeout(tick,0);const interval=setInterval(tick,1000);return()=>{clearTimeout(first);clearInterval(interval);};},[]);function runTimestamp(){try{setOutput(JSON.stringify(timestampToDates(input,unit),null,2));setError("");}catch(e){setError(e instanceof Error?e.message:"Invalid timestamp.");setOutput("");}}function runDate(){try{setOutput(JSON.stringify(dateToTimestamp(dateInput),null,2));setError("");}catch(e){setError(e instanceof Error?e.message:"Invalid date.");setOutput("");}}return <Panel><p className="rounded-xl bg-blue-50 p-3 text-sm">Current Unix timestamp: <strong className="font-mono">{now??"Loading…"}</strong></p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="font-semibold">Unix timestamp<input value={input} onChange={e=>setInput(e.target.value)} className={smallInputClass}/></label><label className="font-semibold">Unit<select value={unit} onChange={e=>setUnit(e.target.value as typeof unit)} className={smallInputClass}><option value="seconds">Seconds</option><option value="milliseconds">Milliseconds</option></select></label></div><Actions><button type="button" onClick={runTimestamp} className={primaryClass}>Convert timestamp</button><button type="button" onClick={()=>{setInput(String(now??1700000000));setUnit("seconds");}} className={secondaryClass}>Use current</button></Actions><label className="mt-6 block font-semibold">Human date and time<input type="datetime-local" value={dateInput} onChange={e=>setDateInput(e.target.value)} className={smallInputClass}/></label><Actions><button type="button" onClick={runDate} className={primaryClass}>Convert date</button><button type="button" onClick={()=>{setInput("");setDateInput("");setOutput("");setError("");}} className={secondaryClass}>Clear</button></Actions>{error&&<Status message={error} error/>}<Output value={output}/></Panel>}

function UrlTool(){const[input,setInput]=useState("");const[output,setOutput]=useState("");const[scope,setScope]=useState<"component"|"full">("component");const[error,setError]=useState("");function run(action:"encode"|"decode"){try{setOutput(transformUrl(input,action,scope));setError("");}catch(e){setOutput("");setError(e instanceof Error?e.message:"Invalid URL text.");}}return <Panel><LabeledTextarea label="URL or component" value={input} onChange={setInput}/><label className="mt-3 block font-semibold">Encoding scope<select value={scope} onChange={e=>setScope(e.target.value as typeof scope)} className={smallInputClass}><option value="component">Query component</option><option value="full">Full URL</option></select></label><Actions><button type="button" onClick={()=>run("encode")} className={primaryClass}>Encode</button><button type="button" onClick={()=>run("decode")} className={secondaryClass}>Decode</button><button type="button" onClick={()=>setInput("https://example.com/search?q=مرحبا world")} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setInput("");setOutput("");setError("");}} className={secondaryClass}>Clear</button></Actions>{error&&<Status message={error} error/>}<Output value={output}/></Panel>}

function HashTool(){const[input,setInput]=useState("");const[algorithm,setAlgorithm]=useState<"SHA-256"|"SHA-384"|"SHA-512">("SHA-256");const[output,setOutput]=useState("");const[error,setError]=useState("");async function run(){try{setOutput(await generateHash(input,algorithm));setError("");}catch(e){setOutput("");setError(e instanceof Error?e.message:"Hashing failed.");}}return <Panel><LabeledTextarea label="Plaintext" value={input} onChange={setInput}/><label className="mt-3 block font-semibold">Algorithm<select value={algorithm} onChange={e=>setAlgorithm(e.target.value as typeof algorithm)} className={smallInputClass}>{["SHA-256","SHA-384","SHA-512"].map(value=><option key={value}>{value}</option>)}</select></label><Actions><button type="button" onClick={run} className={primaryClass}>Generate hash</button><button type="button" onClick={()=>setInput("abc")} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setInput("");setOutput("");setError("");}} className={secondaryClass}>Clear</button></Actions>{error&&<Status message={error} error/>}<Output value={output} label={`${algorithm} digest`}/></Panel>}

function HtmlTool(){const[input,setInput]=useState("");const[output,setOutput]=useState("");return <Panel><LabeledTextarea label="HTML entity input" value={input} onChange={setInput}/><Actions><button type="button" onClick={()=>setOutput(encodeHtml(input))} className={primaryClass}>Encode entities</button><button type="button" onClick={()=>setOutput(decodeHtml(input))} className={secondaryClass}>Decode entities</button><button type="button" onClick={()=>setInput('<a title="Example & test">Hello</a>')} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setInput("");setOutput("");}} className={secondaryClass}>Clear</button></Actions><Output value={output}/></Panel>}

function DiffTool(){const[original,setOriginal]=useState("");const[modified,setModified]=useState("");const[lines,setLines]=useState<DiffLine[]>([]);const[error,setError]=useState("");function run(){try{setLines(diffLines(original,modified));setError("");}catch(e){setLines([]);setError(e instanceof Error?e.message:"Unable to compare text.");}}const plain=lines.map(line=>`${line.type==="added"?"+":line.type==="removed"?"-":" "} ${line.text}`).join("\n");return <Panel><div className="grid gap-5 lg:grid-cols-2"><LabeledTextarea label="Original text" value={original} onChange={setOriginal}/><LabeledTextarea label="Modified text" value={modified} onChange={setModified}/></div><Actions><button type="button" onClick={run} className={primaryClass}>Compare text</button><button type="button" onClick={()=>{setOriginal("alpha\nbeta\ngamma");setModified("alpha\nbeta changed\ngamma\ndelta");}} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setOriginal("");setModified("");setLines([]);setError("");}} className={secondaryClass}>Clear</button><CopyButton value={plain}/></Actions>{error&&<Status message={error} error/>}<div aria-live="polite" className="mt-5 overflow-hidden rounded-xl border font-mono text-sm">{lines.length===0?<p className="p-4 text-slate-500">Differences will appear here.</p>:lines.map((line,index)=><div key={`${index}-${line.text}`} className={`break-words px-4 py-1 ${line.type==="added"?"bg-emerald-50 text-emerald-900":line.type==="removed"?"bg-red-50 text-red-900":"bg-white text-slate-600"}`}><span aria-hidden>{line.type==="added"?"+":line.type==="removed"?"−":" "}</span> {line.text||" "}</div>)}</div></Panel>}

function SlugTool(){const[input,setInput]=useState("");const[output,setOutput]=useState("");const[lowercase,setLowercase]=useState(true);const[separator,setSeparator]=useState<"-"|"_">("-");function run(){setOutput(generateSlug(input,{lowercase,separator}));}return <Panel><LabeledTextarea label="Text" value={input} onChange={setInput}/><div className="mt-3 flex flex-wrap gap-6"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={lowercase} onChange={e=>setLowercase(e.target.checked)}/> Lowercase</label><label className="text-sm font-semibold">Separator <select value={separator} onChange={e=>setSeparator(e.target.value as typeof separator)} className="ml-2 rounded-lg border p-2"><option value="-">Hyphen (-)</option><option value="_">Underscore (_)</option></select></label></div><Actions><button type="button" onClick={run} className={primaryClass}>Generate slug</button><button type="button" onClick={()=>setInput("SignalRate أدوات المطورين 2026")} className={secondaryClass}>Use example</button><button type="button" onClick={()=>{setInput("");setOutput("");}} className={secondaryClass}>Clear</button></Actions><Output value={output}/></Panel>}

export function DeveloperTool({mode}:{mode:DeveloperToolSlug}){switch(mode){case"json-formatter":return <JsonTool/>;case"json-validator":return <JsonTool validator/>;case"base64":return <Base64Tool/>;case"jwt-decoder":return <JwtTool/>;case"uuid-generator":return <UuidGenerator/>;case"uuid-validator":return <UuidValidator/>;case"unix-timestamp":return <TimestampTool/>;case"url-encoder":return <UrlTool/>;case"hash-generator":return <HashTool/>;case"html-encoder":return <HtmlTool/>;case"text-diff":return <DiffTool/>;case"slug-generator":return <SlugTool/>;default:return <TrafficTool mode={mode}/>;}}
