/* eslint-disable @next/next/no-img-element -- generated local SVG data URL is not an optimizable remote image */
"use client";

import {useState} from "react";
import {buildQrPayload,convertData,csvToJson,downloadTime,formatSql,formatYaml,jsonToCsv,jsonToXml,jsonToYaml,parseCron,parseUserAgent,qrSvg,testRegex,xmlToJson,yamlToJson,type QrKind} from "@/lib/traffic-tools";
import type {DeveloperToolSlug} from "@/lib/developer-tools";

const area="mt-2 min-h-44 w-full resize-y rounded-xl border border-slate-300 bg-white p-4 font-mono text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const input="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 font-mono outline-none focus:border-blue-500";
const primary="rounded-xl bg-[#315efb] px-4 py-2.5 font-semibold text-white disabled:opacity-50";
const secondary="rounded-xl border border-slate-300 bg-white px-4 py-2.5 font-semibold text-slate-700";
function Panel({children}:{children:React.ReactNode}){return <section className="mt-8 rounded-2xl border bg-white p-5 shadow-sm sm:p-6">{children}</section>}
function Actions({children}:{children:React.ReactNode}){return <div className="mt-4 flex flex-wrap gap-2">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block font-semibold">{label}{children}</label>}
function Result({value,error}:{value:string;error:string}){return <div aria-live="polite" className={`mt-5 rounded-xl p-4 ${error?"bg-red-50 text-red-800":"bg-slate-950 text-slate-100"}`}><pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap break-words text-sm">{error||value||"Result will appear here."}</pre></div>}
function AsyncTool({mode}:{mode:"sql"|"yaml"|"json-yaml"|"csv-json"|"xml-json"}){const[text,setText]=useState("");const[out,setOut]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function run(reverse=false){setBusy(true);setError("");try{const result=mode==="sql"?await formatSql(text):mode==="yaml"?await formatYaml(text):mode==="json-yaml"?(reverse?await yamlToJson(text):await jsonToYaml(text)):mode==="csv-json"?(reverse?await jsonToCsv(text):await csvToJson(text)):(reverse?await jsonToXml(text):await xmlToJson(text));setOut(result)}catch(e){setOut("");setError(e instanceof Error?e.message:"Unable to process input.")}finally{setBusy(false)}}const labels=mode==="json-yaml"?["JSON → YAML","YAML → JSON"]:mode==="csv-json"?["CSV → JSON","JSON → CSV"]:mode==="xml-json"?["XML → JSON","JSON → XML"]:[mode==="sql"?"Format SQL":"Format and validate YAML",""];return <Panel><Field label="Input"><textarea value={text} onChange={e=>setText(e.target.value)} className={area}/></Field><Actions><button disabled={busy} onClick={()=>run(false)} className={primary}>{labels[0]}</button>{labels[1]&&<button disabled={busy} onClick={()=>run(true)} className={secondary}>{labels[1]}</button>}<button onClick={()=>{setText("");setOut("");setError("")}} className={secondary}>Clear</button></Actions><Result value={out} error={error}/></Panel>}
function RegexTool(){const[pattern,setPattern]=useState("(cat)");const[flags,setFlags]=useState("gi");const[text,setText]=useState("Cat dog cat");const[out,setOut]=useState("");const[error,setError]=useState("");function run(){try{setOut(JSON.stringify(testRegex(pattern,text,flags),null,2));setError("")}catch(e){setOut("");setError(e instanceof Error?e.message:"Invalid pattern.")}}return <Panel><div className="grid gap-4 sm:grid-cols-[1fr_8rem]"><Field label="Pattern"><input value={pattern} onChange={e=>setPattern(e.target.value)} className={input}/></Field><Field label="Flags"><input value={flags} onChange={e=>setFlags(e.target.value)} className={input}/></Field></div><Field label="Test text"><textarea value={text} onChange={e=>setText(e.target.value)} className={area}/></Field><Actions><button onClick={run} className={primary}>Test expression</button></Actions><Result value={out} error={error}/></Panel>}
function CronTool(){const[expression,setExpression]=useState("*/15 9 * * 1-5");const[out,setOut]=useState("");const[error,setError]=useState("");function run(){try{setOut(JSON.stringify(parseCron(expression),null,2));setError("")}catch(e){setOut("");setError(e instanceof Error?e.message:"Invalid cron expression.")}}return <Panel><Field label="Five-field cron expression (UTC)"><input value={expression} onChange={e=>setExpression(e.target.value)} className={input}/></Field><div className="mt-3 flex flex-wrap gap-2">{[["Every 15 minutes","*/15 * * * *"],["Weekdays at 09:00","0 9 * * 1-5"],["Daily at midnight","0 0 * * *"]].map(([label,value])=><button key={value} onClick={()=>setExpression(value)} className={secondary}>{label}</button>)}</div><Actions><button onClick={run} className={primary}>Explain and preview</button></Actions><Result value={out} error={error}/></Panel>}
function UaTool(){const[text,setText]=useState("");const[out,setOut]=useState("");const[error,setError]=useState("");function run(){try{setOut(JSON.stringify(parseUserAgent(text),null,2));setError("")}catch(e){setOut("");setError(e instanceof Error?e.message:"Unable to parse user agent.")}}return <Panel><Field label="User-Agent string"><textarea value={text} onChange={e=>setText(e.target.value)} className={area}/></Field><Actions><button onClick={run} className={primary}>Parse locally</button><button onClick={()=>setText(navigator.userAgent)} className={secondary}>Use this browser</button></Actions><Result value={out} error={error}/></Panel>}
function QrTool(){const[kind,setKind]=useState<QrKind>("url");const[value,setValue]=useState("https://signal-rate.com");const[extra,setExtra]=useState("");const[svg,setSvg]=useState("");const[error,setError]=useState("");async function run(){try{const payload=buildQrPayload(kind,value,{message:extra,password:extra,security:"WPA"});setSvg(await qrSvg(payload));setError("")}catch(e){setSvg("");setError(e instanceof Error?e.message:"Unable to generate QR code.")}}function download(){const url=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="signalrate-qr.svg";anchor.click();URL.revokeObjectURL(url)}return <Panel><div className="grid gap-4 sm:grid-cols-2"><Field label="Payload type"><select value={kind} onChange={e=>setKind(e.target.value as QrKind)} className={input}>{["text","url","email","phone","sms","wifi"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label={kind==="wifi"?"Network name":"Content"}><input value={value} onChange={e=>setValue(e.target.value)} className={input}/></Field></div>{["sms","wifi"].includes(kind)&&<Field label={kind==="wifi"?"Wi-Fi password":"SMS message"}><input value={extra} onChange={e=>setExtra(e.target.value)} className={input}/></Field>}<Actions><button onClick={run} className={primary}>Generate locally</button>{svg&&<button onClick={download} className={secondary}>Download SVG</button>}</Actions>{error&&<Result value="" error={error}/>} {svg&&<div className="mt-5 flex justify-center rounded-xl bg-slate-50 p-5"><img src={`data:image/svg+xml;base64,${btoa(svg)}`} alt="Generated QR code" width="256" height="256"/></div>}</Panel>}
function UnitTool(){const[value,setValue]=useState("1");const[from,setFrom]=useState("GB");const[to,setTo]=useState("MB");const[speed,setSpeed]=useState("100");const[out,setOut]=useState("");const[error,setError]=useState("");const units=["bit","Kbit","Mbit","Gbit","byte","KB","MB","GB","TB"];function run(){try{const converted=convertData(Number(value),from,to);const estimate=downloadTime(Number(value),from,Number(speed),"Mbit");setOut(JSON.stringify({converted_value:converted,to,download_at_mbit_per_second:Number(speed),estimated_seconds:estimate.seconds,estimated_time:estimate.human},null,2));setError("")}catch(e){setOut("");setError(e instanceof Error?e.message:"Invalid values.")}}return <Panel><div className="grid gap-4 sm:grid-cols-4"><Field label="Value"><input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)} className={input}/></Field><Field label="From"><select value={from} onChange={e=>setFrom(e.target.value)} className={input}>{units.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="To"><select value={to} onChange={e=>setTo(e.target.value)} className={input}>{units.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Speed (Mbit/s)"><input type="number" min="0.01" value={speed} onChange={e=>setSpeed(e.target.value)} className={input}/></Field></div><Actions><button onClick={run} className={primary}>Convert and estimate</button></Actions><Result value={out} error={error}/></Panel>}
void QrTool;
void UnitTool;
function DataUnitToolWithMode(){
 const[value,setValue]=useState("1"),[from,setFrom]=useState("GB"),[to,setTo]=useState("MB"),[binary,setBinary]=useState(false),[out,setOut]=useState(""),[error,setError]=useState("");const units=["bit","Kbit","Mbit","Gbit","byte","KB","MB","GB","TB"];
 function run(){try{setOut(JSON.stringify({input:Number(value),from,result:convertData(Number(value),from,to,binary),to,convention:binary?"binary powers of 1024":"decimal SI powers of 1000",bits_per_byte:8},null,2));setError("")}catch(e){setOut("");setError(e instanceof Error?e.message:"Invalid values.")}}
 return <Panel><div className="grid gap-4 sm:grid-cols-3"><Field label="Value"><input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)} className={input}/></Field><Field label="From"><select value={from} onChange={e=>setFrom(e.target.value)} className={input}>{units.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="To"><select value={to} onChange={e=>setTo(e.target.value)} className={input}>{units.map(v=><option key={v}>{v}</option>)}</select></Field></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={binary} onChange={e=>setBinary(e.target.checked)}/> Use binary multiples (1024) instead of decimal SI multiples (1000)</label><Actions><button onClick={run} className={primary}>Convert locally</button></Actions><Result value={out} error={error}/></Panel>
}
function QrToolWithOptions(){
 const[kind,setKind]=useState<QrKind>("url"),[value,setValue]=useState("https://signal-rate.com"),[extra,setExtra]=useState(""),[size,setSize]=useState(256),[level,setLevel]=useState<"L"|"M"|"Q"|"H">("M"),[svg,setSvg]=useState(""),[error,setError]=useState("");
 async function run(){try{setSvg(await qrSvg(buildQrPayload(kind,value,{message:extra,password:extra,security:"WPA"}),size,level));setError("")}catch(e){setSvg("");setError(e instanceof Error?e.message:"Unable to generate QR code.")}}
 function download(){const url=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"})),anchor=document.createElement("a");anchor.href=url;anchor.download="signalrate-qr.svg";anchor.click();URL.revokeObjectURL(url)}
 return <Panel><div className="grid gap-4 sm:grid-cols-2"><Field label="Payload type"><select value={kind} onChange={e=>setKind(e.target.value as QrKind)} className={input}>{["text","url","email","phone","sms","wifi"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label={kind==="wifi"?"Network name":"Content"}><input value={value} onChange={e=>setValue(e.target.value)} className={input}/></Field>{["sms","wifi"].includes(kind)&&<Field label={kind==="wifi"?"Wi-Fi password":"SMS message"}><input value={extra} onChange={e=>setExtra(e.target.value)} className={input}/></Field>}<Field label="Output size"><select value={size} onChange={e=>setSize(Number(e.target.value))} className={input}>{[192,256,384,512].map(v=><option key={v} value={v}>{v} × {v}</option>)}</select></Field><Field label="Error correction"><select value={level} onChange={e=>setLevel(e.target.value as typeof level)} className={input}>{["L","M","Q","H"].map(v=><option key={v}>{v}</option>)}</select></Field></div><Actions><button onClick={run} className={primary}>Generate locally</button>{svg&&<button onClick={download} className={secondary}>Download SVG</button>}</Actions>{error&&<Result value="" error={error}/>} {svg&&<div className="mt-5 flex justify-center overflow-auto rounded-xl bg-slate-50 p-5"><img src={`data:image/svg+xml;base64,${btoa(svg)}`} alt="Generated QR code" width={size} height={size}/></div>}</Panel>
}
export function TrafficTool({mode}:{mode:DeveloperToolSlug}){if(mode==="regex-tester")return <RegexTool/>;if(mode==="cron-generator")return <CronTool/>;if(mode==="user-agent-parser")return <UaTool/>;if(mode==="qr-code-generator")return <QrToolWithOptions/>;if(mode==="data-unit-converter")return <DataUnitToolWithMode/>;const mapped=mode==="sql-formatter"?"sql":mode==="yaml-formatter"?"yaml":mode==="json-yaml-converter"?"json-yaml":mode==="csv-json-converter"?"csv-json":"xml-json";return <AsyncTool mode={mapped}/>}
