<?php

return [
    'network' => [
        ['Is It Down?', '/network/is-it-down', 'is site down website down availability موقع متوقف ping 网站'], ['Ping & Latency Test', '/network/ping-test', 'ping latency jitter ping test اختبار زمن الاستجابة latencia'], ['Certificate Chain Checker', '/network/certificate-chain-checker', 'certificate chain ssl chain سلسلة الشهادة'], ['Certificate Decoder', '/network/certificate-decoder', 'x509 certificate decoder decode pem'], ['CSR Decoder', '/network/csr-decoder', 'csr decoder certificate request'], ['TLS Version Checker', '/network/tls-version-checker', 'tls checker tls 1.2 tls 1.3'], ['HTTPS Checker', '/network/https-checker', 'https checker hsts redirect certificate'],
        ['Email Security', '/network/email-security', 'email security spf dkim dmarc'], ['Internet Speed Test', '/network/speed-test', 'speed test internet download upload ping latency jitter cloudflare'],
        ['What Is My IP', '/network/what-is-my-ip', 'ip address public ipv4 ipv6'], ['IP Lookup', '/network/ip-lookup', 'ip geolocation network'], ['ASN Lookup', '/network/asn-lookup', 'asn autonomous system'], ['IP WHOIS / RDAP', '/network/ip-whois', 'whois rdap rir'], ['Reverse DNS', '/network/reverse-dns', 'ptr reverse dns'], ['Hostname Lookup', '/network/hostname-lookup', 'hostname a aaaa'], ['DNS Lookup', '/network/dns-lookup', 'dns mx txt cname ns soa caa'], ['SPF Checker', '/network/spf-checker', 'email spf sender policy'], ['DKIM Checker', '/network/dkim-checker', 'email dkim selector public key'], ['DMARC Checker', '/network/dmarc-checker', 'email dmarc policy alignment'], ['SSL Certificate Checker', '/network/ssl-checker', 'ssl tls certificate expiry'], ['Redirect Checker', '/network/redirect-checker', 'http redirect chain'], ['HTTP Header Checker', '/network/http-header-checker', 'http response security headers'], ['Port Checker', '/network/port-checker', 'port tcp reachable'], ['IP Blacklist Checker', '/network/ip-blacklist-check', 'blacklist dnsbl reputation'], ['Subnet Calculator', '/network/subnet-calculator', 'subnet mask'], ['CIDR Calculator', '/network/cidr-calculator', 'cidr netmask range'], ['IP Calculator', '/network/ip-calculator', 'private public classify ipv6'], ['Bandwidth Calculator', '/network/bandwidth-calculator', 'bandwidth bit byte rate'], ['Download Time Calculator', '/network/download-time-calculator', 'download transfer time speed'],
    ],
    'developer' => [
        ['Secure Password Generator', '/developer-tools/password-generator', 'password generator strong random password パスワード contraseña senha passwort كلمة مرور'],
        ['JSON Formatter', '/developer-tools/json-formatter', 'json format pretty print minify'], ['JSON Validator', '/developer-tools/json-validator', 'json validate syntax'], ['URL Encoder / Decoder', '/developer-tools/url-encoder', 'url encode decode percent unicode'], ['Base64 Encoder / Decoder', '/developer-tools/base64', 'base64 encode decode base64url unicode'], ['JWT Decoder', '/developer-tools/jwt-decoder', 'jwt token header payload signature'], ['UUID Generator', '/developer-tools/uuid-generator', 'uuid guid v4 generate'], ['UUID Validator', '/developer-tools/uuid-validator', 'uuid guid validate version variant'], ['Unix Timestamp Converter', '/developer-tools/unix-timestamp', 'unix timestamp epoch seconds milliseconds'], ['Hash Generator', '/developer-tools/hash-generator', 'hash sha256 sha512 digest'], ['HTML Encoder / Decoder', '/developer-tools/html-encoder', 'html entities escape'], ['Text Diff', '/developer-tools/text-diff', 'text diff compare'], ['Slug Generator', '/developer-tools/slug-generator', 'slug seo url'], ['Regex Tester', '/developer-tools/regex-tester', 'regex regular expression pattern'], ['Cron Expression Generator / Parser', '/developer-tools/cron-generator', 'cron crontab schedule'], ['SQL Formatter', '/developer-tools/sql-formatter', 'sql query format'], ['YAML Formatter / Validator', '/developer-tools/yaml-formatter', 'yaml yml validate format'], ['JSON ↔ YAML Converter', '/developer-tools/json-yaml-converter', 'json yaml convert'], ['CSV ↔ JSON Converter', '/developer-tools/csv-json-converter', 'csv json convert'], ['XML ↔ JSON Converter', '/developer-tools/xml-json-converter', 'xml json convert'], ['User-Agent Parser', '/developer-tools/user-agent-parser', 'user agent browser device'], ['QR Code Generator', '/developer-tools/qr-code-generator', 'qr code wifi url'], ['Data Unit Converter', '/developer-tools/data-unit-converter', 'data bandwidth bits bytes'],
    ],
    'calculators' => [
        ['SignalRate Calculators', '/calculators', 'calculators calculator hub'], ['Percentage Calculator', '/calculators/percentage-calculator', 'percentage percent calculator porcentaje प्रतिशत نسبة'], ['Exact Age Calculator', '/calculators/age-calculator', 'age birthday calculator edad âge العمر'], ['Date Calculator', '/calculators/date-calculator', 'date difference days between dates'], ['Time Calculator', '/calculators/time-calculator', 'time duration midnight'], ['Loan Payment Calculator', '/calculators/loan-calculator', 'loan payment monthly interest préstamo قرض'], ['Compound Interest Calculator', '/calculators/compound-interest-calculator', 'compound interest investment growth'], ['Currency Converter', '/calculators/currency-converter', 'currency exchange rate العملات divisas'], ['Unit Converter', '/calculators/unit-converter', 'unit measurement converter'], ['Data Usage Calculator', '/calculators/data-usage-calculator', 'data usage internet mobile calculator'],
    ],
];
