import Link from"next/link";import type{MobilePlan,VerificationStatus}from"@/lib/types";
export function VerificationBadge({status,date}:{status:VerificationStatus;date?:string|null}){const styles={verified:"bg-emerald-100 text-emerald-800",stale:"bg-amber-100 text-amber-800",unverified:"bg-slate-100 text-slate-700",failed:"bg-rose-100 text-rose-800"};const label=status.charAt(0).toUpperCase()+status.slice(1);return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${styles[status]}`}>{label}{date?` · checked ${new Date(date).toLocaleDateString("en-GB")}`:" · not checked"}</span>}
export function PriceDisplay({plan}:{plan:MobilePlan}){if(plan.price===null)return <span className="text-slate-500">Price unavailable</span>;return <span><strong className="text-2xl">{new Intl.NumberFormat("en-GB",{style:"currency",currency:plan.currency??"GBP"}).format(Number(plan.price))}</strong><span className="text-sm text-slate-500"> / {plan.billing_period??"period"}</span></span>}
export function DataAllowance({plan}:{plan:MobilePlan}){return <span>{plan.unlimited_data?"Unlimited data":plan.data_allowance_mb!==null?`${Number((plan.data_allowance_mb/1024).toFixed(2))} GB data`:"Data not stated"}</span>}
export function OperatorBadge({plan}:{plan:MobilePlan}){return <span className="rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold">{plan.operator.brand??plan.operator.name}</span>}
export function PlanFeature({enabled,label}:{enabled:boolean|null;label:string}){return <span className={enabled?"text-emerald-700":"text-slate-400"}>{enabled?"✓":"—"} {label}</span>}
export const Feature=PlanFeature;
export function CompareButton({selected,onClick}:{selected:boolean;onClick:()=>void}){return <button type="button" aria-pressed={selected} onClick={onClick} className={`rounded-lg px-3 py-2 text-sm font-semibold ${selected?"bg-[#315efb] text-white":"border border-slate-300 bg-white"}`}>{selected?"Selected":"Compare"}</button>}
export function PlanCard({plan,selected,onCompare}:{plan:MobilePlan;selected?:boolean;onCompare?:()=>void}){return <article className="flex h-full flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col items-start gap-3"><OperatorBadge plan={plan}/><VerificationBadge status={plan.verification_status} date={plan.last_verified_at}/></div><h2 className="mt-4 text-xl font-bold">{plan.name}</h2><div className="mt-3"><PriceDisplay plan={plan}/></div><p className="mt-3 font-semibold"><DataAllowance plan={plan}/></p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm"><PlanFeature enabled={plan.five_g} label="5G"/><PlanFeature enabled={plan.esim} label="eSIM"/><PlanFeature enabled={plan.hotspot_allowed} label="Hotspot"/></div><p className="mt-3 text-sm text-slate-500">{plan.contract_length_months?`${plan.contract_length_months}-month contract`:"Contract term not stated"}{plan.cost_per_gb!==null?` · £${plan.cost_per_gb}/GB`:""}</p><div className="mt-auto flex items-center justify-between gap-3 pt-5"><Link className="font-semibold text-[#315efb]" href={`/mobile-plans/${plan.country.iso2.toLowerCase()}/${plan.operator.slug}/${plan.slug}`}>Plan details</Link>{onCompare&&<CompareButton selected={!!selected} onClick={onCompare}/>}</div></article>}
export function PriceHistory({plan}:{plan:MobilePlan}){if(!plan.price_history?.length)return <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No historical price observations have been published for this plan.</p>;const prices=plan.price_history.map(p=>Number(p.new_price??p.price));const min=Math.min(...prices),max=Math.max(...prices);const points=prices.map((value,index)=>`${(index/(Math.max(1,prices.length-1)))*280},${90-((value-min)/(Math.max(1,max-min)))*70}`).join(" ");return <div><svg viewBox="0 0 280 100" role="img" aria-label="Observed plan price history" className="h-40 w-full rounded-xl bg-slate-50 p-3"><polyline fill="none" stroke="#315efb" strokeWidth="4" points={points}/></svg><ol className="mt-3 space-y-2 text-sm">{plan.price_history.map(p=><li key={p.id}>{new Date(p.observed_at??p.effective_from).toLocaleDateString("en-GB")}: {p.currency} {p.new_price??p.price} <VerificationBadge status={p.verification_status}/></li>)}</ol></div>}
