import type { Metadata } from "next";
import Link from "next/link";
import { PlanExplorer } from "@/components/plan-explorer";
import { Footer, Header } from "@/components/site-chrome";
import { apiGet } from "@/lib/api";
import type { MobilePlanResponse } from "@/lib/types";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Compare UK Mobile Plans", description: "Filter UK mobile plans by price, data, 5G, eSIM and contract length with source and freshness details.", alternates: { canonical: "/mobile-plans/uk" }, openGraph: { title: "Compare UK Mobile Plans | SignalRate", description: "A transparent, source-attributed UK mobile plan finder.", url: "/mobile-plans/uk", type: "website" } };

export default async function Page() {
  const { data, meta } = await apiGet<MobilePlanResponse>("/mobile-plans/country/GB?sort=cheapest&per_page=50");
  const verified = data.filter(plan => plan.verification_status === "verified");
  const cheapest = verified.filter(plan => plan.price !== null).sort((a, b) => Number(a.price) - Number(b.price))[0];
  const operators = new Set(verified.map(plan => plan.operator.id)).size;
  const jsonLd = { "@context": "https://schema.org", "@type": "CollectionPage", name: "UK mobile plan comparison", url: "https://signalrate.com/mobile-plans/uk", mainEntity: verified.length ? { "@type": "ItemList", numberOfItems: verified.length, itemListElement: verified.map((plan, index) => ({ "@type": "ListItem", position: index + 1, name: plan.name, url: `https://signalrate.com/mobile-plans/uk/${plan.operator.slug}/${plan.slug}` })) } : undefined };

  return <><Header /><main className="shell py-14"><nav className="text-sm text-slate-500"><Link href="/">Home</Link> / <Link href="/mobile-plans">Mobile plans</Link> / UK</nav><header className="mt-6 max-w-3xl"><p className="font-semibold text-[#315efb]">United Kingdom</p><h1 className="mt-2 text-4xl font-bold md:text-5xl">Compare UK mobile plans</h1><p className="mt-4 text-lg text-slate-600">Filter source-attributed plans by real allowances and costs. SignalRate does not recommend a “best” plan or treat stale data as current.</p></header><section aria-label="Verified dataset summary" className="my-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><b className="text-2xl">{verified.length}</b><p className="text-sm text-slate-500">verified plans</p></div><div className="rounded-2xl border bg-white p-5"><b className="text-2xl">{operators}</b><p className="text-sm text-slate-500">operators represented</p></div><div className="rounded-2xl border bg-white p-5"><b className="text-2xl">{cheapest?.price ? `£${cheapest.price}` : "—"}</b><p className="text-sm text-slate-500">lowest verified recurring price</p></div></section><div className="mb-5 flex flex-wrap gap-3"><Link href="/mobile-plans/uk/find" className="rounded-lg bg-[#10213b] px-4 py-2 font-semibold text-white">Open guided finder</Link><Link href="/carriers/united-kingdom" className="rounded-lg border bg-white px-4 py-2 font-semibold">UK carrier directory</Link></div><PlanExplorer initialPlans={data} /><section className="mt-12 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">How rankings work</h2><p className="mt-3 text-slate-600">Cheapest uses recurring price. Most data puts unlimited plans first. Cost per GB applies only to finite allowances. Shortest contract uses the stated minimum term. No subjective score is added.</p></article><article className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Freshness and coverage</h2><p className="mt-3 text-slate-600">This page currently has {meta.total} published records. Every card states its verification status and checked date; missing facts remain visibly unknown.</p></article></section><section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Related UK telecom resources</h2><div className="mt-4 flex flex-wrap gap-4 font-semibold text-[#315efb]"><Link href="/calling-codes/44">UK calling code +44</Link><Link href="/tools/e164-phone-formatter">E.164 phone formatter</Link><Link href="/tools/mcc-mnc-lookup">MCC/MNC lookup</Link><Link href="/tools/sms-segment-calculator">SMS segment calculator</Link></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></main><Footer /></>;
}
