export type AuthorityLink={path:string;label:string;context:string};
export type Guide={slug:string;title:string;description:string;intro:string;sections:{heading:string;body:string[]}[];related:AuthorityLink[]};

export const guides:Guide[]=[
  {slug:"internet-speed",title:"How to understand an internet speed test",description:"Learn what download, upload, latency and jitter measure, why results vary, and how to run a fair browser speed test.",intro:"A speed test is a short sample of one device, connection and route at one moment. The four headline measurements answer different questions, so no single number describes an entire connection.",sections:[
    {heading:"Download, upload, latency and jitter",body:["Download speed is the rate at which the browser receives data; upload speed is the rate at which it sends data. SignalRate reports both in Mbps. Latency is the round-trip delay in milliseconds, while jitter describes variation between latency samples.","Streaming and large downloads mainly need sustained download throughput. Video calls, gaming and remote desktops are also sensitive to latency and jitter. A fast download result cannot compensate for an unstable or congested path."]},
    {heading:"Run a representative test",body:["Pause large transfers, use the connection you want to assess, and test more than once at different times. Wi-Fi distance, other users, browser load, VPNs and routing can all change a result.","SignalRate loads Cloudflare's browser test only after you press Start. Test traffic travels between your browser and Cloudflare rather than through the SignalRate application server. Results are displayed in the page and are not stored by SignalRate."]},
    {heading:"What the result cannot prove",body:["A browser test does not certify an ISP's entire network, diagnose every Wi-Fi problem, or guarantee the same speed to every destination. Compare repeated measurements and, when troubleshooting, test both Ethernet and Wi-Fi before drawing a conclusion."]}],
    related:[{path:"/network/speed-test",label:"Run the Internet Speed Test",context:"Measure browser-to-Cloudflare download, upload, latency and jitter."},{path:"/network/ping-test",label:"Ping & Latency Test",context:"Focus on delay and jitter with a lighter browser measurement."},{path:"/network/what-is-my-ip",label:"What Is My IP?",context:"See the public address presented by the current connection."}]},
  {slug:"ip-address",title:"Public IP addresses, privacy and troubleshooting",description:"Understand public IPv4 and IPv6 addresses, NAT, changing addresses, geolocation limits and safe IP troubleshooting.",intro:"A public IP address identifies an internet connection at the network layer. It is useful for routing and diagnosis, but it is not a reliable identity for a person or an exact physical location.",sections:[
    {heading:"Public versus private addresses",body:["Routers commonly give devices private addresses and translate their traffic through one public address using NAT. IPv6 can give devices globally routable addresses while firewalls still control unsolicited access.","Consumer public addresses may change after a reconnect or provider lease renewal. Mobile networks, carrier-grade NAT, VPNs and corporate gateways can also make many users appear behind one address."]},
    {heading:"Geolocation and ownership limits",body:["IP geolocation is an estimate derived from registry and commercial routing data. It may identify a country, region or network, but should not be treated as a street address. An ASN identifies the network announcing a route, not necessarily the end user."]},
    {heading:"Privacy-aware diagnosis",body:["Share an IP only when it is necessary for support, and avoid publishing logs that combine addresses with account or session identifiers. SignalRate's public-IP tool requests the result from its network API, displays it to you, and does not send the value to advertising or analytics events."]}],
    related:[{path:"/network/what-is-my-ip",label:"Check your public IP",context:"View the address that SignalRate currently sees."},{path:"/network/ip-lookup",label:"IP Lookup",context:"Review source-aware network and location context."},{path:"/network/asn-lookup",label:"ASN Lookup",context:"Inspect the autonomous system associated with a route."}]},
  {slug:"json",title:"JSON formatting, validation and debugging",description:"A practical guide to JSON syntax, safe formatting, common parse errors and the difference between data and executable code.",intro:"JSON is a text format for values such as objects, arrays, strings, numbers, booleans and null. Formatting changes whitespace; it must not change the underlying tokens or meaning.",sections:[
    {heading:"Valid JSON syntax",body:["Property names and strings use double quotes. Commas separate members and array items but cannot trail the final item. Comments, undefined, NaN and single-quoted strings are not part of standard JSON.","A validator parses the complete document and reports the first syntax problem it can locate. Fixing that error may reveal a later one, so validate again after each correction."]},
    {heading:"Formatting and compacting",body:["Pretty-printing adds indentation and line breaks for review. Compacting removes insignificant whitespace for transport. Neither operation should reorder data deliberately, evaluate code, or silently repair invalid input."]},
    {heading:"Handle sensitive data carefully",body:["Tokens, credentials and personal records often appear in API payloads. Remove secrets before sharing examples. SignalRate's formatter runs in your browser; the input is not uploaded, stored or sent to advertising or analytics."]}],
    related:[{path:"/developer-tools/json-formatter",label:"JSON Formatter",context:"Format, compact or validate JSON locally in the browser."},{path:"/developer-tools/json-validator",label:"JSON Validator",context:"Check syntax without changing the document."},{path:"/developer-tools/text-diff",label:"Text Diff",context:"Compare two serialized payloads line by line."}]},
  {slug:"password-security",title:"Password generation and account security",description:"Learn how password length, randomness, uniqueness and password managers work together to protect accounts.",intro:"A strong password is generated from an unpredictable source, long enough for its character set, and unique to one account. Complexity rules alone cannot rescue a reused or predictably chosen password.",sections:[
    {heading:"Randomness and length",body:["SignalRate uses the browser's cryptographic random-number generator, crypto.getRandomValues, and rejection sampling to avoid modulo bias. The displayed entropy estimate assumes every generated choice remains uniformly random.","Longer generated passwords usually add more search space than cosmetic substitutions in a memorable word. Site-specific maximum lengths and allowed symbols can still constrain the result."]},
    {heading:"Store passwords safely",body:["Use a reputable password manager so every account can have a unique value. Prefer passkeys or multi-factor authentication when available. Never email a master password or paste credentials into an untrusted form."]},
    {heading:"Limits of a generator",body:["A generated password cannot protect a compromised device, a phishing session, insecure recovery questions or a breached service. Treat the output as a credential immediately and do not reuse examples shown in documentation."]}],
    related:[{path:"/developer-tools/password-generator",label:"Password Generator",context:"Create a password locally with configurable character groups."},{path:"/developer-tools/hash-generator",label:"Hash Generator",context:"Calculate a digest locally; hashing is not password storage guidance."},{path:"/developer-tools/uuid-generator",label:"UUID Generator",context:"Generate identifiers—not passwords or authentication secrets."}]},
  {slug:"time-zones",title:"Time zones, UTC offsets and daylight-saving time",description:"Understand IANA time zones, UTC offsets, DST transitions and reliable conversion across regions.",intro:"A UTC offset is a number for one instant; an IANA time-zone identifier contains the rules needed to determine offsets across dates. That distinction matters whenever daylight-saving rules change.",sections:[
    {heading:"Use a named IANA zone",body:["Identifiers such as Europe/Paris or Asia/Tokyo let software apply historical and scheduled rules. Abbreviations such as CST are ambiguous, and a fixed offset such as UTC+01:00 does not describe future DST transitions."]},
    {heading:"Ambiguous and missing local times",body:["When clocks move backward, one local time may occur twice. When clocks move forward, a range of local times may not exist. Store important instants in UTC and retain the intended zone for display and scheduling."]},
    {heading:"Conversion limits",body:["Browser results depend on the time-zone database shipped with the user's runtime. Governments can change rules with little notice, so verify critical future schedules close to the event."]}],
    related:[{path:"/tools/time-zone-converter",label:"Time Zone Converter",context:"Compare one date and time across named IANA zones."},{path:"/developer-tools/unix-timestamp",label:"Unix Timestamp Converter",context:"Convert an instant between Unix time and human-readable dates."}]},
  {slug:"currency-exchange",title:"Currency conversion and reference exchange rates",description:"Understand ECB reference rates, cross-rate calculations, spreads, fees and why a converter is not a trade quote.",intro:"A reference-rate conversion is an indicative calculation, not a promise that a bank, card or exchange will settle at the same price.",sections:[
    {heading:"How cross-rates are calculated",body:["SignalRate uses cached European Central Bank reference rates and converts through their shared euro base. It displays the source and reference date so an older working-day rate is not mistaken for a live market quote."]},
    {heading:"Why the paid amount differs",body:["Providers can add a spread, commission, card fee or fixed transfer charge. Settlement timing, weekends and holidays can also change the applied rate. Compare the final provider quote rather than the reference result alone."]},
    {heading:"Appropriate use",body:["Use the calculator for estimates, reconciliation checks and broad comparisons. Confirm a regulated provider's terms before a purchase, transfer, tax filing or other financial decision."]}],
    related:[{path:"/calculators/currency-converter",label:"Currency Converter",context:"Calculate an indicative conversion from cached ECB reference rates."},{path:"/methodology",label:"SignalRate methodology",context:"See how sources, dates, caching and limitations are disclosed."}]},
  {slug:"ssl-tls",title:"SSL/TLS certificates and HTTPS checks",description:"Learn what TLS certificates prove, how chains and hostname validation work, and what browser-based checks cannot establish.",intro:"TLS protects data in transit and authenticates a hostname through a certificate chain. A valid certificate does not by itself prove that a website or its content is trustworthy.",sections:[
    {heading:"Certificate validation",body:["A client checks the hostname, validity period, signatures and path to a trusted root. Missing intermediates, expired certificates and name mismatches are common causes of HTTPS failure."]},
    {heading:"Protocol and configuration",body:["TLS versions and cipher negotiation affect compatibility and security. Redirects, HSTS and proxy configuration also influence the connection users actually receive."]},
    {heading:"Interpret remote checks carefully",body:["Results describe the public endpoint reachable at test time. CDNs and regional routing can produce different certificates or protocol paths. SignalRate restricts remote requests to public targets and applies SSRF protections."]}],
    related:[{path:"/network/ssl-checker",label:"SSL Certificate Checker",context:"Inspect the public certificate presented by a hostname."},{path:"/network/certificate-chain-checker",label:"Certificate Chain Checker",context:"Review the supplied intermediate chain."},{path:"/network/tls-version-checker",label:"TLS Version Checker",context:"Check supported protocol versions on a public endpoint."}]},
  {slug:"dns",title:"DNS records, resolution and troubleshooting",description:"Understand recursive resolution, common DNS record types, caching, TTLs and practical DNS troubleshooting.",intro:"DNS maps names to records through a distributed, cached system. A correct record can take time to appear everywhere, and different resolvers can temporarily return different answers.",sections:[
    {heading:"Resolution and caching",body:["A recursive resolver follows delegations from the root through authoritative name servers, then caches the answer for its TTL. Local operating systems, browsers and applications may add their own caches."]},
    {heading:"Common record types",body:["A and AAAA records map names to IPv4 and IPv6 addresses. CNAME aliases one name to another. MX routes mail, TXT carries policy or verification text, and NS identifies authoritative servers."]},
    {heading:"Troubleshooting method",body:["Check the exact hostname and record type, compare authoritative and recursive answers, inspect TTLs, then verify DNSSEC or delegation when applicable. Never infer that a missing record proves ownership or intent."]}],
    related:[{path:"/network/dns-lookup",label:"DNS Lookup",context:"Query common DNS record types for a hostname."},{path:"/network/reverse-dns",label:"Reverse DNS Lookup",context:"Look for a PTR name associated with an IP address."},{path:"/network/email-security",label:"Email Security Tools",context:"Inspect SPF, DKIM and DMARC records."}]},
];

export const guideBySlug=Object.fromEntries(guides.map(guide=>[guide.slug,guide])) as Record<string,Guide>;
export const guidePaths=new Set(guides.map(guide=>`/guides/${guide.slug}`));
export const guideForTool:Record<string,string>={
  "/network/speed-test":"internet-speed","/network/ping-test":"internet-speed","/network/what-is-my-ip":"ip-address","/network/ip-lookup":"ip-address","/network/asn-lookup":"ip-address",
  "/developer-tools/json-formatter":"json","/developer-tools/json-validator":"json","/developer-tools/password-generator":"password-security","/tools/time-zone-converter":"time-zones","/developer-tools/unix-timestamp":"time-zones",
  "/calculators/currency-converter":"currency-exchange","/network/ssl-checker":"ssl-tls","/network/certificate-chain-checker":"ssl-tls","/network/tls-version-checker":"ssl-tls","/network/dns-lookup":"dns","/network/reverse-dns":"dns",
};
