export type DeveloperToolSlug =
  | "json-formatter"
  | "json-validator"
  | "base64"
  | "jwt-decoder"
  | "uuid-generator"
  | "uuid-validator"
  | "unix-timestamp"
  | "url-encoder"
  | "hash-generator"
  | "html-encoder"
  | "text-diff"
  | "slug-generator"
  | "regex-tester"
  | "cron-generator"
  | "sql-formatter"
  | "yaml-formatter"
  | "json-yaml-converter"
  | "csv-json-converter"
  | "xml-json-converter"
  | "user-agent-parser"
  | "qr-code-generator"
  | "data-unit-converter";

export type DeveloperToolDefinition = {
  slug: DeveloperToolSlug;
  name: string;
  category: "Data" | "Encoding" | "Security / Tokens" | "Identifiers" | "Time / Date" | "Text / URL" | "Web" | "Developer Utilities" | "Converters" | "Calculators";
  description: string;
  keywords: string[];
  explanationTitle: string;
  explanation: string;
  notes: string[];
  related: DeveloperToolSlug[];
  status: "active";
};

export const developerTools: DeveloperToolDefinition[] = [
  {slug:"json-formatter",name:"JSON Formatter",category:"Data",description:"Pretty-print, compact, and validate JSON without uploading it.",keywords:["json","format json","pretty print","minify"],explanationTitle:"Pretty JSON without changing its data",explanation:"JSON is a text format for structured data. Pretty printing adds indentation for people; minifying removes insignificant whitespace for transport. SignalRate preserves the original JSON number and string tokens while changing whitespace only.",notes:["Common errors include trailing commas, single-quoted strings, and unquoted property names.","Valid JSON supports objects, arrays, strings, numbers, booleans, and null."],related:["json-validator","base64","jwt-decoder"],status:"active"},
  {slug:"json-validator",name:"JSON Validator",category:"Data",description:"Check JSON syntax and locate parsing errors by line and column.",keywords:["json","validate json","json syntax"],explanationTitle:"What makes JSON valid?",explanation:"Valid JSON follows a strict grammar: property names and strings use double quotes, escape sequences are defined, and trailing commas are not allowed. Validation checks syntax; it does not prove that data matches an application schema.",notes:["The reported location points near where parsing stopped.","Use the formatter after validation to make nested structures easier to inspect."],related:["json-formatter","base64"],status:"active"},
  {slug:"base64",name:"Base64 Encoder / Decoder",category:"Encoding",description:"Encode Unicode text as Base64 or decode Base64 and Base64URL safely.",keywords:["base64","base64 encode","base64 decode","base64url"],explanationTitle:"Base64 is encoding, not encryption",explanation:"Base64 represents bytes using printable characters so binary or Unicode data can travel through text-oriented systems. Anyone can decode it, so Base64 must never be treated as secrecy or password protection.",notes:["UTF-8 converts Unicode text to bytes before encoding.","Base64URL replaces + and / and commonly omits padding for URLs and JWTs."],related:["jwt-decoder","json-formatter","hash-generator"],status:"active"},
  {slug:"jwt-decoder",name:"JWT Decoder",category:"Security / Tokens",description:"Inspect JWT header and payload claims locally without verifying trust.",keywords:["jwt","decode jwt","token","header payload signature"],explanationTitle:"Header, payload, and signature",explanation:"A JWT usually contains three Base64URL segments. The header describes the signing algorithm, the payload carries claims, and the final segment contains signature bytes. Reading those segments does not prove who created the token.",notes:["Decoded only — signature not verified.","exp, iat, and nbf are NumericDate values measured in Unix seconds."],related:["base64","unix-timestamp","json-formatter"],status:"active"},
  {slug:"uuid-generator",name:"UUID Generator",category:"Identifiers",description:"Generate 1, 5, 10, or 100 cryptographically secure UUID v4 values.",keywords:["uuid","uuid generator","guid","uuid v4"],explanationTitle:"Random UUID v4 identifiers",explanation:"A UUID is a 128-bit identifier designed to be unique without a central counter. Version 4 UUIDs use secure random bytes with standard version and variant bits, making collisions extraordinarily unlikely for ordinary application workloads.",notes:["Generation uses the browser crypto API, never Math.random.","UUIDs are identifiers, not secrets or authorization tokens."],related:["uuid-validator","hash-generator"],status:"active"},
  {slug:"uuid-validator",name:"UUID Validator",category:"Identifiers",description:"Validate common UUID forms and identify their version and variant.",keywords:["uuid","uuid validator","guid validate","uuid version"],explanationTitle:"UUID versions and variants",explanation:"The UUID version nibble describes how an identifier was produced. The RFC variant is encoded separately. Validation checks structure and bits; it cannot tell whether an identifier exists in another system.",notes:["Canonical, braced, and urn:uuid forms are accepted.","Version 4 indicates random generation; other versions use different schemes."],related:["uuid-generator"],status:"active"},
  {slug:"unix-timestamp",name:"Unix Timestamp Converter",category:"Time / Date",description:"Convert Unix seconds or milliseconds to UTC, local, ISO, and RFC dates.",keywords:["unix timestamp","epoch","timestamp converter","milliseconds"],explanationTitle:"Unix time and the epoch",explanation:"Unix time counts elapsed seconds from 1970-01-01T00:00:00Z. Some systems store milliseconds instead. UTC is unambiguous, while local display depends on the browser’s time zone.",notes:["Negative values represent dates before the Unix epoch.","The current timestamp updates in your browser and is not page-cached."],related:["jwt-decoder"],status:"active"},
  {slug:"url-encoder",name:"URL Encoder / Decoder",category:"Text / URL",description:"Encode or decode full URLs and individual query components without corrupting Unicode.",keywords:["url encode","url decode","percent encoding","encodeuricomponent"],explanationTitle:"Full URLs versus components",explanation:"A full URL contains structural characters such as : / ? and # that encodeURI leaves intact. A query value is a component, so encodeURIComponent also escapes those structural characters when they belong to the value.",notes:["Malformed percent escapes produce an explicit error.","Form encoding may use + for spaces; this tool follows JavaScript URI rules."],related:["html-encoder","slug-generator"],status:"active"},
  {slug:"hash-generator",name:"Hash Generator",category:"Security / Tokens",description:"Generate SHA-256, SHA-384, or SHA-512 digests locally with Web Crypto.",keywords:["hash","sha256","sha-256","sha512","checksum"],explanationTitle:"Hashing is not encryption",explanation:"A cryptographic hash maps input to a fixed-size digest and cannot be decrypted. SHA-256, SHA-384, and SHA-512 are useful for integrity checks, but raw fast hashes are not suitable password storage without a dedicated password-hashing scheme.",notes:["The same bytes produce the same hexadecimal digest.","Plaintext stays in the browser and is never sent to SignalRate."],related:["base64","uuid-generator"],status:"active"},
  {slug:"html-encoder",name:"HTML Encoder / Decoder",category:"Web",description:"Encode HTML-sensitive characters or decode entities as safe text.",keywords:["html encode","html decode","html entities","escape html"],explanationTitle:"Entities and safe display",explanation:"HTML entities represent characters such as <, >, &, quotes, and Unicode code points. Encoding is useful when text must appear literally in markup. Decoded output here is always rendered as text and never executed as HTML.",notes:["Entity encoding is context-specific and does not replace a complete XSS defense.","Never insert untrusted decoded text with unsafe innerHTML."],related:["url-encoder","text-diff"],status:"active"},
  {slug:"text-diff",name:"Text Diff",category:"Developer Utilities",description:"Compare two texts line by line and identify additions and removals locally.",keywords:["text diff","compare text","line diff","difference"],explanationTitle:"How line-level diff works",explanation:"A line diff finds a common subsequence and marks lines present only in the original as removed and lines present only in the modified text as added. Adjacent removals and additions describe a changed block.",notes:["The comparison runs locally and preserves line text.","Inputs are bounded to keep the browser responsive."],related:["json-formatter","slug-generator"],status:"active"},
  {slug:"slug-generator",name:"Slug Generator",category:"Text / URL",description:"Create clean URL slugs while retaining meaningful non-Latin scripts.",keywords:["slug","slug generator","seo url","url slug"],explanationTitle:"Readable URL slugs",explanation:"A slug is the human-readable path segment of a URL. Good slugs are concise, consistently separated, and stable. This tool normalizes Unicode but retains letters and numbers from non-Latin writing systems instead of deleting them.",notes:["Choose hyphens for conventional web paths or underscores where required.","Transliteration is not guessed; original scripts remain intact."],related:["url-encoder","text-diff"],status:"active"},
  {slug:"regex-tester",name:"Regex Tester",category:"Developer Utilities",description:"Test bounded JavaScript regular expressions, matches, groups, and positions locally.",keywords:["regex","regular expression","capture groups","pattern tester"],explanationTitle:"Patterns, flags and capture groups",explanation:"A regular expression describes text patterns. Flags change matching behavior, while parentheses capture useful submatches. SignalRate uses the browser JavaScript dialect, limits input, and blocks common nested-quantifier shapes that can cause excessive backtracking.",notes:["Results include zero-based start and end positions.","This is not a guarantee that every expensive pattern can be detected statically."],related:["json-formatter","text-diff"],status:"active"},
  {slug:"cron-generator",name:"Cron Expression Generator / Parser",category:"Time / Date",description:"Build and explain standard five-field cron expressions with UTC execution previews.",keywords:["cron","crontab","cron expression","schedule"],explanationTitle:"Five fields, one explicit dialect",explanation:"This tool supports conventional five-field cron: minute, hour, day of month, month, and day of week. It previews UTC times and implements the usual OR behavior when both day fields are restricted.",notes:["Quartz seconds/year fields and scheduler-specific aliases are not supported.","Confirm the target scheduler time zone and dialect before deployment."],related:["unix-timestamp"],status:"active"},
  {slug:"sql-formatter",name:"SQL Formatter",category:"Developer Utilities",description:"Format common SQL syntax locally without connecting to or executing a database.",keywords:["sql formatter","format sql","pretty sql","query formatter"],explanationTitle:"Formatting is not execution or validation",explanation:"Formatting adds consistent whitespace and keyword casing so queries are easier to review. It does not run SQL, verify table names, prove database semantics, or make an unsafe query safe.",notes:["Input never leaves the browser.","Review vendor-specific syntax after formatting."],related:["text-diff","json-formatter"],status:"active"},
  {slug:"yaml-formatter",name:"YAML Formatter / Validator",category:"Data",description:"Safely validate and format YAML locally using the core schema.",keywords:["yaml","yaml formatter","yaml validator","yml"],explanationTitle:"Readable YAML with safe parsing",explanation:"YAML represents structured data with indentation, mappings, sequences, and scalar values. This tool uses a safe core schema and bounded aliases; it does not construct application-specific classes or execute tags.",notes:["Indentation is significant.","Validation checks syntax, not an application schema."],related:["json-yaml-converter","json-formatter"],status:"active"},
  {slug:"json-yaml-converter",name:"JSON ↔ YAML Converter",category:"Converters",description:"Convert JSON and safely parsed YAML in either direction without uploading data.",keywords:["json yaml","yaml json","convert yaml","convert json"],explanationTitle:"Two representations of structured data",explanation:"JSON is strict and machine-oriented; YAML can be more concise for configuration. Conversion preserves ordinary mappings, sequences, scalars, booleans, and null values, but comments and presentation details may not survive.",notes:["YAML uses the safe core schema.","Aliases are bounded to prevent expansion abuse."],related:["yaml-formatter","xml-json-converter","csv-json-converter"],status:"active"},
  {slug:"csv-json-converter",name:"CSV ↔ JSON Converter",category:"Converters",description:"Convert RFC-style CSV rows and JSON object arrays locally.",keywords:["csv json","json csv","convert csv","spreadsheet json"],explanationTitle:"Rows, headers and structured objects",explanation:"CSV stores rows of delimited fields, while JSON represents named values and nested structures. CSV-to-JSON treats the first row as headers; JSON-to-CSV expects an array of flat objects.",notes:["Quoted commas and line breaks are parsed correctly.","Nested JSON values may need separate normalization before CSV conversion."],related:["json-yaml-converter","xml-json-converter","json-formatter"],status:"active"},
  {slug:"xml-json-converter",name:"XML ↔ JSON Converter",category:"Converters",description:"Convert bounded XML and single-root JSON structures locally.",keywords:["xml json","json xml","convert xml","xml parser"],explanationTitle:"Elements, attributes and JSON objects",explanation:"XML describes nested elements and attributes; JSON represents objects and arrays. The converter retains attributes with explicit keys and blocks DOCTYPE/entity declarations to avoid unsafe expansion behavior.",notes:["JSON-to-XML requires one root element.","Schema or DTD validation is not performed."],related:["json-yaml-converter","csv-json-converter","html-encoder"],status:"active"},
  {slug:"user-agent-parser",name:"User-Agent Parser",category:"Web",description:"Identify common browser, OS, engine, and device hints from a user-agent string.",keywords:["user agent","ua parser","browser detection","device parser"],explanationTitle:"User agents are hints, not identity",explanation:"User-agent strings often expose browser and platform tokens, but clients can omit or spoof them. This parser reports only common recognizable patterns and returns Unknown when evidence is ambiguous.",notes:["Never use a user-agent as authentication or identity proof.","Client Hints may differ from the legacy user-agent string."],related:["regex-tester","url-encoder"],status:"active"},
  {slug:"qr-code-generator",name:"QR Code Generator",category:"Encoding",description:"Generate downloadable SVG QR codes locally for text, URLs, email, phone, SMS, or Wi-Fi.",keywords:["qr","qr code","wifi qr","url qr"],explanationTitle:"Static QR payloads without tracking",explanation:"A QR code encodes text into a machine-readable grid. SignalRate generates a static SVG in your browser; it does not create redirect links, analytics, expiring codes, or store the payload.",notes:["Anyone who scans the code can read its payload.","Verify sensitive Wi-Fi or contact content before sharing."],related:["url-encoder","data-unit-converter"],status:"active"},
  {slug:"data-unit-converter",name:"Data Unit Converter",category:"Calculators",description:"Convert bits, bytes, decimal network units, and optional binary storage units accurately.",keywords:["data unit","bits bytes","mb gb","bandwidth converter"],explanationTitle:"Bits, bytes, decimal and binary units",explanation:"One byte contains eight bits. Network rates normally use decimal multiples (1 Mbit = 1,000,000 bits), while binary storage multiples use powers of 1024. The selected convention is always shown.",notes:["Uppercase B means bytes; lowercase bit means bits.","Binary mode changes multipliers, not the eight-bits-per-byte relationship."],related:["json-formatter","qr-code-generator"],status:"active"},
];

export const developerToolBySlug = Object.fromEntries(developerTools.map(tool => [tool.slug, tool])) as Record<DeveloperToolSlug, DeveloperToolDefinition>;

export function developerToolPath(slug: DeveloperToolSlug) {
  return `/developer-tools/${slug}`;
}
