export type NetworkMode="my-ip"|"ip-lookup"|"asn"|"rdap"|"reverse-dns"|"hostname"|"dns"|"port"|"blacklist"|"subnet"|"cidr"|"ip-calculator"|"spf"|"dkim"|"dmarc"|"ssl"|"redirect"|"headers"|"bandwidth"|"download-time";
export type NetworkToolDefinition={mode:NetworkMode;name:string;path:string;group:string;description:string;heading:string;explanation:string;local?:boolean;related:NetworkMode[]};
const tool=(mode:NetworkMode,name:string,path:string,group:string,description:string,heading:string,explanation:string,related:NetworkMode[],local=false):NetworkToolDefinition=>({mode,name,path,group,description,heading,explanation,related,local});
export const networkTools:NetworkToolDefinition[]=[
tool("my-ip","What Is My IP","/network/what-is-my-ip","IP tools","See the public address observed by SignalRate.","What can an IP address reveal?","A public IP identifies a connection endpoint, not a person. Location and ownership metadata can be incomplete or outdated.",["ip-lookup","asn","rdap"]),
tool("ip-lookup","IP Lookup","/network/ip-lookup","IP tools","Inspect an IPv4 or IPv6 address with source-aware metadata.","IPv4, IPv6 and approximate metadata","SignalRate validates both address forms and clearly labels unknown provider fields.",["asn","rdap","reverse-dns"]),
tool("asn","ASN Lookup","/network/asn-lookup","IP tools","Normalize an ASN and query configured routing data.","What is an ASN?","An Autonomous System Number identifies a network that announces routes under one routing policy.",["ip-lookup","rdap"]),
tool("rdap","IP WHOIS / RDAP","/network/ip-whois","IP tools","Read structured registration data from the responsible RIR.","What is RDAP?","RDAP is the structured successor to traditional WHOIS and uses official registry bootstrap data.",["ip-lookup","reverse-dns"]),
tool("reverse-dns","Reverse DNS","/network/reverse-dns","IP tools","Find PTR hostnames associated with an IP.","What is reverse DNS?","A PTR hostname is administrative metadata, not proof of who operates a device.",["dns","hostname"]),
tool("hostname","Hostname Lookup","/network/hostname-lookup","DNS tools","Resolve A, AAAA and canonical-name records.","Hostname resolution","Public fully qualified names are resolved while URL schemes and internal-only names are rejected.",["dns","port"]),
tool("dns","DNS Lookup","/network/dns-lookup","DNS tools","Query common public DNS record types.","Understanding DNS records","A and AAAA map names to addresses; MX routes mail; TXT carries policies; NS and SOA describe authority.",["hostname","spf"]),
tool("spf","SPF Checker","/network/spf-checker","Email security","Inspect a domain SPF policy and common risks.","Sender Policy Framework","SPF lists sources authorized to send for a domain. It is one input to authentication, not a deliverability guarantee.",["dkim","dmarc","dns"]),
tool("dkim","DKIM Checker","/network/dkim-checker","Email security","Look up a selected DKIM public key.","DomainKeys Identified Mail","DKIM selectors locate public keys used to validate message signatures. A valid record does not prove every message is signed.",["spf","dmarc","dns"]),
tool("dmarc","DMARC Checker","/network/dmarc-checker","Email security","Parse DMARC policy and reporting tags.","Domain-based authentication policy","DMARC tells receivers how to handle alignment failures and where aggregate reports may be sent.",["spf","dkim","dns"]),
tool("ssl","SSL Certificate Checker","/network/ssl-checker","Web diagnostics","Inspect a public host certificate and expiry.","TLS certificate observations","The backend verifies the presented certificate, hostname, validity period, issuer, and alternative names at check time.",["redirect","headers"]),
tool("redirect","Redirect Checker","/network/redirect-checker","Web diagnostics","Trace up to five validated HTTP redirects.","A safely bounded redirect chain","Every destination is re-resolved and revalidated; private, internal, reserved, and metadata targets are blocked.",["headers","ssl"]),
tool("headers","HTTP Header Checker","/network/http-header-checker","Web diagnostics","Inspect response and common security headers.","Headers describe response behavior","Presence is reported without claiming a site is secure; policies still require contextual review.",["redirect","ssl"]),
tool("port","Port Checker","/network/port-checker","Security and reputation","Test one public host and one TCP port safely.","A deliberately limited reachability check","This is one bounded connection from the backend, not a scanner. Internal and metadata targets are blocked.",["hostname","dns"]),
tool("blacklist","IP Blacklist Checker","/network/ip-blacklist-check","Security and reputation","Check enabled, license-approved reputation sources.","Interpreting blacklist results","Results mean not listed on checked sources, never clean everywhere.",["ip-lookup","rdap"]),
tool("subnet","Subnet Calculator","/network/subnet-calculator","Network calculators","Calculate IPv4 network, broadcast and usable range.","IPv4 subnet boundaries","CIDR determines network and host bits, with explicit handling for /31 and /32.",["cidr","ip-calculator"],true),
tool("cidr","CIDR Calculator","/network/cidr-calculator","Network calculators","Convert CIDR ranges and contiguous IPv4 netmasks.","What is CIDR?","Classless routing expresses a network as an address plus prefix length.",["subnet","ip-calculator"],true),
tool("ip-calculator","IP Calculator","/network/ip-calculator","Network calculators","Classify IPv4 and IPv6 addresses.","Public and special-purpose addresses","Addresses are classified as public, private, loopback, link-local, multicast, or other special-purpose ranges.",["subnet","cidr"],true),
tool("bandwidth","Bandwidth Calculator","/network/bandwidth-calculator","Network calculators","Convert network rates across bit and byte units.","Bits, bytes and rate units","Network rates conventionally use decimal multiples; one byte always equals eight bits.",["download-time","ip-calculator"],true),
tool("download-time","Download Time Calculator","/network/download-time-calculator","Network calculators","Estimate ideal transfer time from size and line rate.","An ideal transfer estimate","The result excludes protocol overhead, congestion, server limits, Wi-Fi conditions, and latency.",["bandwidth","ip-calculator"],true),
];
export const networkToolByMode=Object.fromEntries(networkTools.map(item=>[item.mode,item])) as Record<NetworkMode,NetworkToolDefinition>;
