const LOCAL_LIMIT=200_000;
function limited(input:string,limit=LOCAL_LIMIT){if(input.length>limit)throw new Error(`Input is too large; limit is ${limit.toLocaleString()} characters.`);return input}

export type RegexMatch={match:string;index:number;end:number;groups:(string|null)[];namedGroups:Record<string,string>};
export function testRegex(pattern:string,input:string,flags="g"):RegexMatch[]{
  limited(pattern,256);limited(input,20_000);
  if(!pattern)throw new Error("Enter a regular expression pattern.");
  if(!/^[dgimsuvy]*$/.test(flags)||new Set(flags).size!==flags.length)throw new Error("Flags must be unique JavaScript regex flags.");
  if(/\([^)]*[+*][^)]*\)[+*{]/.test(pattern)||/(?:\.\*|\.\+){2,}/.test(pattern))throw new Error("This potentially catastrophic nested-quantifier pattern is blocked.");
  let regex:RegExp;try{regex=new RegExp(pattern,flags.includes("g")?flags:`${flags}g`)}catch(error){throw new Error(error instanceof Error?error.message:"Invalid regular expression.")}
  const matches:RegexMatch[]=[];let match:RegExpExecArray|null;
  while((match=regex.exec(input))!==null&&matches.length<1000){matches.push({match:match[0],index:match.index,end:match.index+match[0].length,groups:match.slice(1).map(value=>value??null),namedGroups:{...(match.groups??{})}});if(match[0]==="")regex.lastIndex++;}
  return matches;
}

type CronField={values:Set<number>;wildcard:boolean};
const CRON_RANGES:ReadonlyArray<readonly [number,number]>=[[0,59],[0,23],[1,31],[1,12],[0,7]];
function parseCronField(text:string,index:number):CronField{const[min,max]=CRON_RANGES[index];const values=new Set<number>();const wildcard=text==="*";for(const part of text.split(",")){const[base,stepText]=part.split("/");const step=stepText===undefined?1:Number(stepText);if(!Number.isInteger(step)||step<1)throw new Error(`Invalid step in cron field ${index+1}.`);let start=min,end=max;if(base!=="*"){const range=base.split("-");start=Number(range[0]);end=range.length===2?Number(range[1]):start;if(!Number.isInteger(start)||!Number.isInteger(end)||start<min||end>max||start>end)throw new Error(`Value outside ${min}-${max} in cron field ${index+1}.`);}for(let value=start;value<=end;value+=step)values.add(index===4&&value===7?0:value);}if(values.size===0)throw new Error(`Cron field ${index+1} is empty.`);return{values,wildcard}}
export function parseCron(expression:string,from=new Date()):{fields:string[];explanation:string;next:string[]}{const fields=expression.trim().split(/\s+/);if(fields.length!==5)throw new Error("Use five fields: minute hour day-of-month month day-of-week.");const parsed=fields.map(parseCronField);const labels=["minute","hour","day of month","month","day of week"];const explanation=fields.map((value,index)=>`${labels[index]}: ${value==="*"?"every value":value}`).join("; ");const next:string[]=[];const cursor=new Date(from);cursor.setUTCSeconds(0,0);cursor.setUTCMinutes(cursor.getUTCMinutes()+1);const maxChecks=60*24*366*2;for(let checks=0;checks<maxChecks&&next.length<5;checks++,cursor.setUTCMinutes(cursor.getUTCMinutes()+1)){const dom=parsed[2].values.has(cursor.getUTCDate()),dow=parsed[4].values.has(cursor.getUTCDay());const dayMatches=parsed[2].wildcard?dow:parsed[4].wildcard?dom:dom||dow;if(parsed[0].values.has(cursor.getUTCMinutes())&&parsed[1].values.has(cursor.getUTCHours())&&dayMatches&&parsed[3].values.has(cursor.getUTCMonth()+1))next.push(cursor.toISOString());}if(next.length===0)throw new Error("No execution was found within the supported two-year preview window.");return{fields,explanation:`Standard five-field cron (UTC): ${explanation}.`,next}}

export async function formatSql(input:string,dialect="sql"){limited(input);if(!input.trim())throw new Error("Enter SQL to format.");const{format}=await import("sql-formatter");return format(input,{language:dialect as Parameters<typeof format>[1] extends {language?:infer T}?T:never,tabWidth:2,keywordCase:"upper"})}
export async function formatYaml(input:string){limited(input);const YAML=await import("yaml");const document=YAML.parseDocument(input,{schema:"core"});if(document.errors.length)throw new Error(document.errors[0].message);return document.toString({indent:2})}
export async function jsonToYaml(input:string){limited(input);const value=JSON.parse(input);const YAML=await import("yaml");return YAML.stringify(value,{indent:2})}
export async function yamlToJson(input:string){limited(input);const YAML=await import("yaml");const document=YAML.parseDocument(input,{schema:"core"});if(document.errors.length)throw new Error(document.errors[0].message);return JSON.stringify(document.toJS({maxAliasCount:50}),null,2)}

export async function csvToJson(input:string){limited(input);const Papa=(await import("papaparse")).default;const result=Papa.parse<Record<string,string>>(input,{header:true,skipEmptyLines:true});if(result.errors.length)throw new Error(result.errors[0].message);return JSON.stringify(result.data,null,2)}
export async function jsonToCsv(input:string){limited(input);const data=JSON.parse(input);if(!Array.isArray(data)||data.some(row=>!row||typeof row!=="object"||Array.isArray(row)))throw new Error("JSON must be an array of objects.");const Papa=(await import("papaparse")).default;return Papa.unparse(data)}

export async function xmlToJson(input:string){limited(input);const{XMLParser,XMLValidator}=await import("fast-xml-parser");const valid=XMLValidator.validate(input);if(valid!==true)throw new Error(valid.err.msg);if(/<!DOCTYPE|<!ENTITY/i.test(input))throw new Error("DOCTYPE and entity declarations are not supported.");return JSON.stringify(new XMLParser({ignoreAttributes:false,processEntities:false}).parse(input),null,2)}
export async function jsonToXml(input:string){limited(input);const value=JSON.parse(input);if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).length!==1)throw new Error("JSON must be an object with exactly one root element.");const{XMLBuilder}=await import("fast-xml-parser");return new XMLBuilder({ignoreAttributes:false,format:true,processEntities:false}).build(value)}

export function parseUserAgent(input:string){limited(input,4096);const ua=input.trim();if(!ua)throw new Error("Enter a user-agent string.");const browser=/Edg\/([\d.]+)/.exec(ua)?.slice(0,2).map((v,i)=>i?v:"Edge")??/Chrome\/([\d.]+)/.exec(ua)?.slice(0,2).map((v,i)=>i?v:"Chrome")??/Firefox\/([\d.]+)/.exec(ua)?.slice(0,2).map((v,i)=>i?v:"Firefox")??/Version\/([\d.]+).*Safari\//.exec(ua)?.slice(0,2).map((v,i)=>i?v:"Safari")??["Unknown",""];const os=/Windows NT 10\.0/.test(ua)?"Windows":/Android ([\d.]+)/.exec(ua)?.[1]?`Android ${/Android ([\d.]+)/.exec(ua)?.[1]}`:/iPhone OS ([\d_]+)/.exec(ua)?.[1]?`iOS ${/iPhone OS ([\d_]+)/.exec(ua)?.[1].replaceAll("_",".")}`:/Mac OS X ([\d_]+)/.exec(ua)?.[1]?`macOS ${/Mac OS X ([\d_]+)/.exec(ua)?.[1].replaceAll("_",".")}`:/Linux/.test(ua)?"Linux":"Unknown";const device=/Mobile|Android|iPhone/.test(ua)?"Mobile":/Tablet|iPad/.test(ua)?"Tablet":"Desktop or unknown";const engine=/AppleWebKit\/([\d.]+)/.exec(ua)?"WebKit":/Gecko\/\d/.test(ua)?"Gecko":"Unknown";return{browser:browser[0],browserVersion:browser[1]||"Unknown",os,deviceClass:device,engine}}

export type QrKind="text"|"url"|"email"|"phone"|"sms"|"wifi";
export function buildQrPayload(kind:QrKind,value:string,options:{subject?:string;message?:string;password?:string;security?:"WPA"|"WEP"|"nopass";hidden?:boolean}={}):string{limited(value,2048);if(!value.trim())throw new Error("Enter QR content.");switch(kind){case"url":{const url=new URL(value);if(!["http:","https:"].includes(url.protocol))throw new Error("QR URLs must use HTTP or HTTPS.");return url.toString()}case"email":return `mailto:${value}${options.subject||options.message?`?${new URLSearchParams({...(options.subject?{subject:options.subject}:{}),...(options.message?{body:options.message}:{})})}`:""}`;case"phone":return `tel:${value.replace(/\s/g,"")}`;case"sms":return `SMSTO:${value.replace(/\s/g,"")}:${options.message??""}`;case"wifi":return `WIFI:T:${options.security??"WPA"};S:${escapeQr(value)};P:${escapeQr(options.password??"")};H:${options.hidden?"true":"false"};;`;default:return value}}
function escapeQr(value:string){return value.replace(/([\\;,:"])/g,"\\$1")}
export async function qrSvg(payload:string,size=256,level:"L"|"M"|"Q"|"H"="M"){limited(payload,2048);const qrLibrary=await import("qrcode-svg");const QRCode=qrLibrary.default;return new QRCode({content:payload,width:size,height:size,padding:4,ecl:level,join:true,container:"svg-viewbox"}).svg()}

const DECIMAL:Record<string,number>={bit:1,Kbit:1e3,Mbit:1e6,Gbit:1e9,byte:8,KB:8e3,MB:8e6,GB:8e9,TB:8e12};
const BINARY:Record<string,number>={bit:1,Kbit:1024,Mbit:1024**2,Gbit:1024**3,byte:8,KB:8*1024,MB:8*1024**2,GB:8*1024**3,TB:8*1024**4};
export function convertData(value:number,from:string,to:string,binary=false){if(!Number.isFinite(value)||value<0)throw new Error("Enter a non-negative value.");const units=binary?BINARY:DECIMAL;if(!units[from]||!units[to])throw new Error("Unsupported data unit.");return value*units[from]/units[to]}
export function downloadTime(fileSize:number,fileUnit:string,speed:number,speedUnit:string,binary=false){if(speed<=0)throw new Error("Connection speed must be greater than zero.");const seconds=convertData(fileSize,fileUnit,"bit",binary)/convertData(speed,speedUnit,"bit",binary);return{seconds,human:formatDuration(seconds)}}
export function formatDuration(seconds:number){if(!Number.isFinite(seconds))return"Unknown";if(seconds<60)return`${seconds.toFixed(2)} seconds`;const hours=Math.floor(seconds/3600),minutes=Math.floor((seconds%3600)/60),secs=Math.round(seconds%60);return[hours&&`${hours}h`,minutes&&`${minutes}m`,`${secs}s`].filter(Boolean).join(" ")}
